version: '3'
services:
 opengts:
  container_name: opengts
  image: halilintar8/mcsaky-opengts
  ports:
   - 8080:8080
  environment:
    - MYSQL_ROOT_PASSWORD=mysql123
 mysql:
  container_name: opengts_mysql
  image: halilintar8/mcsaky-opengts
  ports:
   - 3306:3306
  environment:
   - MYSQL_ROOT_PASSWORD=mysql123
   
