version: '3'
services:
 opengts:
  container_name: opengts
  image: halilintar8/mcsaky-opengts
  ports:
   - 8080:8080
   - 5055:5055
  environment:
   - MYSQL_ROOT_PASSWORD=mysqlroot
   - MYSQL_DBNAME=gts
   - MYSQL_DBPASS=opengts
   - MYSQL_DBUSER=gts
   - CREATE_DATABASE=true
   - SYSADMIN_PASSWORD=sysadmin
   - MYSQL_SERVICE_HOST=mysql
 mysql:
  container_name: opengts_mysql
  image: mariadb:latest
  ports:
   - 3306:3306
  environment:
   - MYSQL_ROOT_PASSWORD=mysqlroot
   - MYSQL_DBNAME=gts
   - MYSQL_DBPASS=opengts
   - MYSQL_DBUSER=gts
   - CREATE_DATABASE=true
   
